import {
  FileText, Code2, Scissors, Lock, Palette, QrCode, Clock, Regex, FileDiff,
  Hash, Binary, Braces, Type, AlignLeft, Timer, Key, Globe, Monitor,
  Link2, CaseSensitive, Dice5, Image, ScanLine, FileSearch, Keyboard,
  Shield, Sigma, Database, Server, Eye, Rows3, Table, Network, HashIcon as Hash2, Search,
  KeyRound, Fingerprint, Shuffle, Combine, Info, ListOrdered, CalendarDays, FolderTree,
  LetterText,
  Trash2,
  Puzzle,
  type LucideIcon,
} from 'lucide-react'

export interface ToolItem {
  id: string
  name: string
  path: string
  icon: LucideIcon
  description: string
  color?: string
}

export interface ToolCategory {
  id: string
  name: string
  tools: ToolItem[]
}

export const toolCategories: ToolCategory[] = [
  {
    id: 'pdf',
    name: 'PDF 工具',
    tools: [
      {
        id: 'pdf-splitter',
        name: 'PDF 拆分',
        path: '/tools/pdf-splitter',
        icon: Scissors,
        description: '按页码范围拆分 PDF 文件',
        color: '#ff6600',
      },
      {
        id: 'pdf-merge',
        name: 'PDF 合并',
        path: '/tools/pdf-merge',
        icon: Combine,
        description: '合并多个 PDF 文件为一个',
        color: '#00f0ff',
      },
      {
        id: 'pdf-info',
        name: 'PDF 信息',
        path: '/tools/pdf-info',
        icon: Info,
        description: '查看 PDF 页数、大小和元数据',
        color: '#00ff88',
      },
      {
        id: 'pdf-rotate',
        name: 'PDF 旋转',
        path: '/tools/pdf-rotate',
        icon: Scissors,
        description: '旋转 PDF 页面 (90° / 180° / 270°)',
        color: '#b847f0',
      },
      {
        id: 'pdf-reorder',
        name: 'PDF 页面重排',
        path: '/tools/pdf-reorder',
        icon: ListOrdered,
        description: '调整 PDF 页面顺序',
        color: '#ff3366',
      },
      {
        id: 'pdf-remove',
        name: 'PDF 删除页面',
        path: '/tools/pdf-remove',
        icon: Trash2,
        description: '删除指定页码，保留其余',
        color: '#ff3366',
      },
      {
        id: 'pdf-viewer',
        name: 'PDF 阅读器',
        path: '/tools/pdf-viewer',
        icon: Eye,
        description: '上传 PDF 文件，浏览器原生渲染阅读',
        color: '#00f0ff',
      },
    ],
  },
  {
    id: 'codec',
    name: '编解码工具',
    tools: [
      {
        id: 'base64',
        name: 'Base64 编解码',
        path: '/tools/base64',
        icon: Code2,
        description: '文本与 Base64 相互转换，支持图片',
        color: '#00f0ff',
      },
      {
        id: 'url',
        name: 'URL 编解码',
        path: '/tools/url',
        icon: Code2,
        description: 'URL 编码与解码',
        color: '#00f0ff',
      },
      {
        id: 'hash',
        name: '哈希计算',
        path: '/tools/hash',
        icon: Hash,
        description: 'SHA 系列哈希计算，支持文件上传',
        color: '#00ff88',
      },
      {
        id: 'radix',
        name: '进制转换',
        path: '/tools/radix',
        icon: Binary,
        description: '二进制、八进制、十进制、十六进制互转',
        color: '#e6b800',
      },
      {
        id: 'jwt',
        name: 'JWT 解码',
        path: '/tools/jwt',
        icon: Key,
        description: '解码 JWT Token，查看 Header 和 Payload',
        color: '#00f0ff',
      },
      {
        id: 'html-entity',
        name: 'HTML Entity',
        path: '/tools/html-entity',
        icon: Code2,
        description: 'HTML 实体编码与解码',
        color: '#00f0ff',
      },
      {
        id: 'unicode',
        name: 'Unicode 转换',
        path: '/tools/unicode',
        icon: Type,
        description: 'Unicode 转义与反转义 (\\uXXXX)',
        color: '#00f0ff',
      },
      {
        id: 'data-units',
        name: '数据单位换算',
        path: '/tools/data-units',
        icon: Sigma,
        description: 'Bytes/KB/MB/GB/TB/PB 互相换算',
        color: '#ff00aa',
      },
    ],
  },
  {
    id: 'format',
    name: '格式化工具',
    tools: [
      {
        id: 'json',
        name: 'JSON 格式化',
        path: '/tools/json',
        icon: FileText,
        description: 'JSON 美化、压缩与校验',
        color: '#00f0ff',
      },
      {
        id: 'text-diff',
        name: '文本对比',
        path: '/tools/text-diff',
        icon: FileDiff,
        description: '对比两段文本的差异',
        color: '#ff00aa',
      },
      {
        id: 'code-formatter',
        name: '代码格式化',
        path: '/tools/code-formatter',
        icon: Braces,
        description: 'JS/TS/HTML/CSS/SQL/XML 代码格式化',
        color: '#b847f0',
      },
      {
        id: 'markdown',
        name: 'Markdown 预览',
        path: '/tools/markdown',
        icon: FileText,
        description: '实时预览 Markdown 渲染效果',
        color: '#00f0ff',
      },
      {
        id: 'yaml-json',
        name: 'YAML ↔ JSON',
        path: '/tools/yaml-json',
        icon: Braces,
        description: 'YAML 与 JSON 互相转换',
        color: '#ff6600',
      },
      {
        id: 'csv-json',
        name: 'CSV 转 JSON',
        path: '/tools/csv-json',
        icon: Table,
        description: 'CSV 数据与 JSON 数组互相转换',
        color: '#00ff88',
      },
      {
        id: 'escape',
        name: '转义字符',
        path: '/tools/escape',
        icon: Code2,
        description: 'JSON/JS/HTML/SQL 字符串转义与反转义',
        color: '#ff00aa',
      },
      {
        id: 'json-schema',
        name: 'JSON Schema',
        path: '/tools/json-schema',
        icon: FileSearch,
        description: '从 JSON 数据自动生成 JSON Schema',
        color: '#b847f0',
      },
      {
        id: 'json-tree',
        name: 'JSON 树形查看',
        path: '/tools/json-tree',
        icon: FolderTree,
        description: '交互式 JSON 树形视图，折叠展开',
        color: '#00f0ff',
      },
      {
        id: 'json-to-ts',
        name: 'JSON → TypeScript',
        path: '/tools/json-to-ts',
        icon: Braces,
        description: '从 JSON 数据自动生成 TS interface',
        color: '#3178c6',
      },
    ],
  },
  {
    id: 'generator',
    name: '生成器工具',
    tools: [
      {
        id: 'password',
        name: '密码生成器',
        path: '/tools/password',
        icon: Lock,
        description: '生成高强度随机密码',
        color: '#ff3366',
      },
      {
        id: 'qr-code',
        name: '二维码生成',
        path: '/tools/qr-code',
        icon: QrCode,
        description: '将文本转为二维码',
        color: '#00ff88',
      },
      {
        id: 'uuid',
        name: 'UUID 生成器',
        path: '/tools/uuid',
        icon: Type,
        description: '生成 UUID v1/v4/v7',
        color: '#00f0ff',
      },
      {
        id: 'lorem',
        name: 'Lorem Ipsum',
        path: '/tools/lorem',
        icon: AlignLeft,
        description: '生成占位文本，支持中英文',
        color: '#ff00aa',
      },
      {
        id: 'cron',
        name: 'Cron 表达式',
        path: '/tools/cron',
        icon: Timer,
        description: '生成和解析 Cron 定时表达式',
        color: '#e6b800',
      },
      {
        id: 'random',
        name: '随机数生成',
        path: '/tools/random',
        icon: Dice5,
        description: '生成指定范围内的随机数',
        color: '#ff3366',
      },
      {
        id: 'palette',
        name: '调色板',
        path: '/tools/palette',
        icon: Palette,
        description: '生成配色方案和渐变',
        color: '#ff00aa',
      },
      {
        id: 'nanoid',
        name: 'Nano ID 生成',
        path: '/tools/nanoid',
        icon: Type,
        description: '生成紧凑的唯一标识符',
        color: '#00f0ff',
      },
      {
        id: 'random-string',
        name: '随机字符串',
        path: '/tools/random-string',
        icon: Dice5,
        description: '生成随机字符串，自定义字符集',
        color: '#ff00aa',
      },
      {
        id: 'random-color',
        name: '随机颜色',
        path: '/tools/random-color',
        icon: Palette,
        description: '随机生成颜色',
        color: '#ff6600',
      },
      {
        id: 'curl',
        name: 'cURL 生成器',
        path: '/tools/curl',
        icon: Network,
        description: '可视化构建 cURL 命令',
        color: '#ff00aa',
      },
      {
        id: 'db-conn',
        name: '数据库连接串',
        path: '/tools/db-conn',
        icon: Database,
        description: 'MySQL/PostgreSQL/MongoDB 连接字符串生成',
        color: '#00ff88',
      },
    ],
  },
  {
    id: 'network',
    name: '网络工具',
    tools: [
      {
        id: 'ip-lookup',
        name: 'IP 查询',
        path: '/tools/ip-lookup',
        icon: Globe,
        description: '查询 IP 地理位置、ISP、时区等详细信息',
        color: '#00f0ff',
      },
      {
        id: 'user-agent',
        name: 'UA 解析',
        path: '/tools/user-agent',
        icon: Monitor,
        description: '解析 User-Agent，查看浏览器和系统信息',
        color: '#00ff88',
      },
      {
        id: 'url-parser',
        name: 'URL 解析',
        path: '/tools/url-parser',
        icon: Link2,
        description: '解析 URL 的协议、主机、路径、参数',
        color: '#ff00aa',
      },
      {
        id: 'mime',
        name: 'MIME 查询',
        path: '/tools/mime',
        icon: FileSearch,
        description: '根据文件扩展名查询 MIME 类型',
        color: '#b847f0',
      },
      {
        id: 'http-headers',
        name: 'HTTP 请求头',
        path: '/tools/http-headers',
        icon: Server,
        description: '查看当前浏览器环境和请求头信息',
        color: '#00f0ff',
      },
      {
        id: 'ip-validator',
        name: 'IP 验证',
        path: '/tools/ip-validator',
        icon: Shield,
        description: '验证 IPv4 / IPv6 地址格式',
        color: '#00ff88',
      },
    ],
  },
  {
    id: 'text',
    name: '文本工具',
    tools: [
      {
        id: 'text-stats',
        name: '文本统计',
        path: '/tools/text-stats',
        icon: AlignLeft,
        description: '统计字符数、单词数、行数等',
        color: '#00f0ff',
      },
      {
        id: 'case-convert',
        name: '大小写转换',
        path: '/tools/case-convert',
        icon: CaseSensitive,
        description: '大写、小写、驼峰、蛇形等命名转换',
        color: '#ff6600',
      },
      {
        id: 'keycode',
        name: '键盘测试',
        path: '/tools/keycode',
        icon: Keyboard,
        description: '按下键盘查看 keyCode 和 code 值',
        color: '#e6b800',
      },
      {
        id: 'text-sorter',
        name: '文本排序去重',
        path: '/tools/text-sorter',
        icon: ListOrdered,
        description: '行排序、去重、翻转、乱序',
        color: '#00f0ff',
      },
      {
        id: 'char-count',
        name: '字符计数',
        path: '/tools/char-count',
        icon: Type,
        description: '实时字符、单词、行数、字节统计',
        color: '#00ff88',
      },
      {
        id: 'reverse-text',
        name: '文本反转',
        path: '/tools/reverse-text',
        icon: ListOrdered,
        description: '逐字符反转文本',
        color: '#b847f0',
      },
      {
        id: 'remove-empty',
        name: '去空行',
        path: '/tools/remove-empty',
        icon: Trash2,
        description: '移除空行和纯空格行',
        color: '#ff3366',
      },
      {
        id: 'line-number',
        name: '添加行号',
        path: '/tools/line-number',
        icon: ListOrdered,
        description: '为每行添加行号',
        color: '#00f0ff',
      },
      {
        id: 'text-repeat',
        name: '文本重复',
        path: '/tools/text-repeat',
        icon: Type,
        description: '将文本重复 N 次',
        color: '#ff6600',
      },
      {
        id: 'slug',
        name: '文本 URL化',
        path: '/tools/slug',
        icon: Link2,
        description: '文本转 URL 友好格式 (slug)',
        color: '#00f0ff',
      },
    ],
  },
  {
    id: 'image',
    name: '图片工具',
    tools: [
      {
        id: 'image-to-base64',
        name: '图片转 Base64',
        path: '/tools/image-to-base64',
        icon: Image,
        description: '上传图片并转换为 Base64 编码',
        color: '#ff00aa',
      },
      {
        id: 'qr-decode',
        name: '二维码解码',
        path: '/tools/qr-decode',
        icon: ScanLine,
        description: '上传二维码图片并解码内容',
        color: '#00ff88',
      },
      {
        id: 'image-compress',
        name: '图片压缩',
        path: '/tools/image-compress',
        icon: Image,
        description: 'Canvas 纯前端压缩 · 调整尺寸和质量',
        color: '#ff00aa',
      },
    ],
  },
  {
    id: 'other',
    name: '其他工具',
    tools: [
      {
        id: 'color',
        name: '颜色转换',
        path: '/tools/color',
        icon: Palette,
        description: 'HEX、RGB、HSL 互转',
        color: '#ff00aa',
      },
      {
        id: 'timestamp',
        name: '时间戳转换',
        path: '/tools/timestamp',
        icon: Clock,
        description: '时间戳与日期时间互转',
        color: '#e6b800',
      },
      {
        id: 'regex',
        name: '正则测试',
        path: '/tools/regex',
        icon: Regex,
        description: '实时测试正则表达式',
        color: '#00f0ff',
      },
      {
        id: 'date-calculator',
        name: '日期计算器',
        path: '/tools/date-calculator',
        icon: CalendarDays,
        description: '日期加减运算与日期差计算',
        color: '#e6b800',
      },
      {
        id: 'percentage',
        name: '百分比计算',
        path: '/tools/percentage',
        icon: Sigma,
        description: '百分比计算与反算',
        color: '#00f0ff',
      },
      {
        id: 'aspect-ratio',
        name: '宽高比计算',
        path: '/tools/aspect-ratio',
        icon: Rows3,
        description: '计算最简整数比',
        color: '#ff00aa',
      },
      {
        id: 'unit-converter',
        name: '单位换算',
        path: '/tools/unit-converter',
        icon: Sigma,
        description: '长度/重量/温度单位换算',
        color: '#00ff88',
      },
      {
        id: 'stopwatch',
        name: '秒表计时',
        path: '/tools/stopwatch',
        icon: Clock,
        description: '高精度毫秒计时器',
        color: '#00f0ff',
      },
      {
        id: 'color-picker',
        name: '颜色选择器',
        path: '/tools/color-picker',
        icon: Palette,
        description: '精确取色 · HEX/RGB/HSL',
        color: '#ff00aa',
      },
    ],
  },
  {
    id: 'crypto',
    name: '加密工具',
    tools: [
      {
        id: 'aes',
        name: 'AES 加解密',
        path: '/tools/aes',
        icon: Shield,
        description: 'AES-GCM 对称加密与解密',
        color: '#ff3366',
      },
      {
        id: 'hmac',
        name: 'HMAC 计算',
        path: '/tools/hmac',
        icon: KeyRound,
        description: 'HMAC-SHA1/256/512 消息认证码',
        color: '#00f0ff',
      },
      {
        id: 'rsa',
        name: 'RSA 密钥',
        path: '/tools/rsa',
        icon: Fingerprint,
        description: 'RSA 密钥生成、PSS 签名与验签',
        color: '#ff00aa',
      },
      {
        id: 'pbkdf2',
        name: 'PBKDF2 派生',
        path: '/tools/pbkdf2',
        icon: KeyRound,
        description: '基于密码的密钥派生函数',
        color: '#00ff88',
      },
      {
        id: 'hex',
        name: 'Hex 编解码',
        path: '/tools/hex',
        icon: Hash2,
        description: '文本与十六进制互相转换',
        color: '#e6b800',
      },
      {
        id: 'rot13',
        name: 'ROT13',
        path: '/tools/rot13',
        icon: Shuffle,
        description: 'ROT13 / Caesar 古典密码',
        color: '#b847f0',
      },
      {
        id: 'md5',
        name: 'MD5 哈希',
        path: '/tools/md5',
        icon: Hash2,
        description: 'MD5 消息摘要 · 128 位 · 纯 JS 实现',
        color: '#e6b800',
      },
      {
        id: 'crc32',
        name: 'CRC32 校验',
        path: '/tools/crc32',
        icon: Shield,
        description: 'CRC32 循环冗余校验 · 32 位',
        color: '#00ff88',
      },
      {
        id: 'ecdsa',
        name: 'ECDSA 密钥',
        path: '/tools/ecdsa',
        icon: Fingerprint,
        description: '椭圆曲线数字签名密钥对 (P-256/384/521)',
        color: '#ff00aa',
      },
      {
        id: 'hkdf',
        name: 'HKDF 派生',
        path: '/tools/hkdf',
        icon: KeyRound,
        description: 'HMAC 密钥派生函数 (SHA-256/384/512)',
        color: '#00f0ff',
      },
      {
        id: 'base32',
        name: 'Base32 编解码',
        path: '/tools/base32',
        icon: LetterText,
        description: 'Base32 RFC 4648 编码与解码',
        color: '#e6b800',
      },
      {
        id: 'base58',
        name: 'Base58 编解码',
        path: '/tools/base58',
        icon: Binary,
        description: 'Base58 Bitcoin 风格编码 · 无易混淆字符',
        color: '#ff6600',
      },
    ],
  },
  {
    id: 'preview',
    name: '预览工具',
    tools: [
      {
        id: 'html-preview',
        name: 'HTML 预览',
        path: '/tools/html-preview',
        icon: Eye,
        description: '实时预览 HTML 代码渲染效果',
        color: '#ff6600',
      },
      {
        id: 'svg-preview',
        name: 'SVG 预览',
        path: '/tools/svg-preview',
        icon: Image,
        description: '实时预览 SVG 代码',
        color: '#ff00aa',
      },
      {
        id: 'base64-image',
        name: 'Base64 图片',
        path: '/tools/base64-image',
        icon: Image,
        description: 'Base64 字符串转图片预览',
        color: '#00f0ff',
      },
    ],
  },
  {
    id: 'reference',
    name: '参考工具',
    tools: [
      {
        id: 'http-status',
        name: 'HTTP 状态码',
        path: '/tools/http-status',
        icon: Server,
        description: 'HTTP 状态码速查表 (1xx-5xx)',
        color: '#00f0ff',
      },
      {
        id: 'ascii-table',
        name: 'ASCII 码表',
        path: '/tools/ascii-table',
        icon: Hash2,
        description: 'ASCII 字符编码查询表',
        color: '#e6b800',
      },
      {
        id: 'css-units',
        name: 'CSS 单位换算',
        path: '/tools/css-units',
        icon: Rows3,
        description: 'px/em/rem/vw/vh/% 互换算',
        color: '#ff00aa',
      },
      {
        id: 'wcag',
        name: 'WCAG 对比度',
        path: '/tools/wcag',
        icon: Palette,
        description: 'WCAG 2.1 颜色对比度检测',
        color: '#b847f0',
      },
      {
        id: 'color-blind',
        name: '色盲模拟',
        path: '/tools/color-blind',
        icon: Eye,
        description: '模拟色觉障碍视角查看颜色',
        color: '#ff00aa',
      },
      {
        id: 'screen-info',
        name: '屏幕信息',
        path: '/tools/screen-info',
        icon: Monitor,
        description: '查看当前屏幕参数',
        color: '#00f0ff',
      },
      {
        id: 'sound-meter',
        name: '音量检测',
        path: '/tools/sound-meter',
        icon: Monitor,
        description: '麦克风实时音量可视化',
        color: '#00ff88',
      },
    ],
  },
  {
    id: 'more',
    name: '更多工具',
    tools: [
      {
        id: 'strip-html',
        name: 'HTML 清理',
        path: '/tools/strip-html',
        icon: FileText,
        description: '移除 HTML 标签，提取纯文本',
        color: '#ff3366',
      },
      {
        id: 'gradient',
        name: '渐变生成',
        path: '/tools/gradient',
        icon: Palette,
        description: '可视化生成 CSS 渐变代码',
        color: '#ff00aa',
      },
      {
        id: 'find-replace',
        name: '查找替换',
        path: '/tools/find-replace',
        icon: Search,
        description: '文本批量查找替换（支持正则）',
        color: '#00f0ff',
      },
      {
        id: 'plugin-manager',
        name: '插件工坊',
        path: '/tools/plugin-manager',
        icon: Puzzle,
        description: '创建和管理自定义插件',
        color: '#b847f0',
      },
      {
        id: 'morse',
        name: '莫尔斯电码',
        path: '/tools/morse',
        icon: Code2,
        description: '摩尔斯电码编码与解码',
        color: '#e6b800',
      },
      {
        id: 'binary-text',
        name: '二进制文本',
        path: '/tools/binary-text',
        icon: Binary,
        description: '文本与二进制互转',
        color: '#00f0ff',
      },
      {
        id: 'meta-tag',
        name: 'Meta 标签',
        path: '/tools/meta-tag',
        icon: Code2,
        description: '生成 HTML Meta 标签',
        color: '#ff6600',
      },
      {
        id: 'robots',
        name: 'Robots.txt',
        path: '/tools/robots',
        icon: FileText,
        description: '生成 robots.txt 文件',
        color: '#00ff88',
      },
      {
        id: 'emoji-picker',
        name: 'Emoji 选择器',
        path: '/tools/emoji-picker',
        icon: Dice5,
        description: '点击复制 Emoji',
        color: '#ff00aa',
      },
      {
        id: 'draw',
        name: '描画画板',
        path: '/tools/draw',
        icon: Image,
        description: '自由绘制 · Canvas 画板',
        color: '#00f0ff',
      },
      {
        id: 'screen-recorder',
        name: '屏幕录制',
        path: '/tools/screen-recorder',
        icon: Monitor,
        description: '浏览器原生录屏 · WebM 格式',
        color: '#ff3366',
      },
      {
        id: 'white-noise',
        name: '白噪发生器',
        path: '/tools/white-noise',
        icon: Eye,
        description: '白噪/粉噪/棕噪音',
        color: '#00f0ff',
      },
      {
        id: 'font-preview',
        name: '字体预览',
        path: '/tools/font-preview',
        icon: Type,
        description: '实时预览系统字体效果',
        color: '#00ff88',
      },
    ],
  },
]

export const allTools = toolCategories.flatMap((c) => c.tools)

/** Route mapping: tool id → route path (derived from tool definitions) */
export const toolRoutes: Record<string, string> = Object.fromEntries(
  allTools.map(t => [t.id, t.path])
)
